### ISSUE TITLE
Add clarification to documentation

### ISSUE THREAD

**Issue by pell-je** [EvidentSolutions/gradle-beanstalk-plugin#33]
What is the s3Endpoint property?

Is it the bucket name?

I am getting an error when trying to run `deployStaging`

```
Execution failed for task ':deployStaging'.
> null (Service: AWSElasticBeanstalk; Status Code: 404; Error Code: 404 Not Found; Request ID: null; Proxy: null)
```

```
Caused by: com.amazonaws.services.elasticbeanstalk.model.AWSElasticBeanstalkException: null (Service: AWSElasticBeanstalk; Status Code: 404; Error Code: 404 Not Found; Request ID: null; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.doInvoke(AWSElasticBeanstalkClient.java:3532)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:3499)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:3488)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.executeCreateStorageLocation(AWSElasticBeanstalkClient.java:1067)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createStorageLocation(AWSElasticBeanstalkClient.java:1035)
	at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createStorageLocation(AWSElasticBeanstalkClient.java:1079)
	at fi.evident.gradle.beanstalk.BeanstalkDeployer.uploadCodeBundle(BeanstalkDeployer.java:144)
	at fi.evident.gradle.beanstalk.BeanstalkDeployer.deploy(BeanstalkDeployer.java:41)

```

**Comment by komu** [comment]
`s3Endpoint` is not the bucket, but the name of the S3 host that you'll contact to talk with S3. Amazon's term for this is... wait for it... S3 Endpoint. 🙂  

See https://docs.aws.amazon.com/general/latest/gr/s3.html for details and pick one close to you.

Error message without any context is of limited help. I'd need to see the relevant parts of the build file to make limit the space of possible hypotheses to a reasonable size.
